### ISSUE TITLE
[BUG] Trimming the boundingboxes results in inaccurate collisions

### ISSUE THREAD

**Issue by ddh** [reidobandedo/Goat-Of-The-Hill#20]
Although visually we trimmed the boundingbox boxes for the goat, I'm not quite sure it worked.
- The boundingbox of the goat is able to float off of a platform. The goat's bounding box and the platform's don't even touch but the goat doesn't fall off.

**Comment by reidobandedo** [comment]
@Jazzmatazz has been working on this to make sure the goat's aren't floating above the platforms.

**Comment by ddh** [comment]
Trimming boundingboxes is fixed now.
