### ISSUE TITLE
Error in console when using Howler (not game-breaking)

### ISSUE THREAD

**Issue by ddh** [reidobandedo/Goat-Of-The-Hill#21]
I get this error whenever howler loads an audio resource:

`XMLHttpRequest cannot load file:///C:/Users/Duy/git/goat/audio/bensound-jazzyfrenchy.mp3. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.`

**Comment by ddh** [comment]
Note to self; need to prevent Goats from recreating the music resources each time a goat is constructed.

**Comment by rainfordr** [comment]
@DuyH Did you ever find a solution to the cross origin requests error? I get the same thing loading a resource using Howler at the moment.

**Comment by ddh** [comment]
@rainfordr This warning popped up for me whenever I ran my game locally; Howler is grabbing the sound file from local but the protocols don't support that. Instead grab resource files from http/https, a server, etc instead of hard coding the location of your file from your computer. Otherwise, Howler won't be able to find the resource file if the game is on the web and looking for that directory which doesn't exist.

SO explains this better than I can: http://stackoverflow.com/questions/10752055/cross-origin-requests-are-only-supported-for-http-error-when-loading-a-local
