### ISSUE TITLE
Making Goats & platforms smaller + making Canvas bigger

### ISSUE THREAD

**Issue by reidobandedo** [reidobandedo/Goat-Of-The-Hill#24]
As per Marriott's suggestion from prototype feedback

**Comment by ddh** [comment]
We still need to make the canvas bigger. To an appropriate aspect ratio common for webgames:

http://gamedevelopment.tutsplus.com/articles/quick-tip-what-is-the-best-screen-resolution-for-your-game--gamedev-14723
