### ISSUE TITLE
Blue goat can't jump to the left while running.

### ISSUE THREAD

**Issue by suchk** [reidobandedo/Goat-Of-The-Hill#51]
Probably due to the alt key binding, since Green goat works fine.

**Comment by ddh** [comment]
We should change the key bindings anyways for submission. Holding down to change and attack is a little awkward as well.

**Comment by ddh** [comment]
This _might_ be an issue with how many keys you can press at the same time on your keyboard? I wasn't able to replicate. We still need to rebind the keys to more sensible keys for the release.
