### ISSUE TITLE
Final round scores don't reflect in-round scores

### ISSUE THREAD

**Issue by suchk** [reidobandedo/Goat-Of-The-Hill#59]
Sometimes the wrong goat will be declared the winner.

**Comment by ddh** [comment]
Not sure the cause of that but looking at PlayGame, I can see some optimizations/improvements to score checking. ie no need to update scores when you can pull them directly from the goats, among other things. I'll take a look after I finish up my tasks

**Comment by Jazzmatazz** [comment]
Hey! I am checking into this problem. I did see some redundant code which could definitely be cleaned up. Also didn't realize it wasn't displaying correctly so I'll be sure to watch that.
