### ISSUE TITLE
Timer should alert players that game is ending 

### ISSUE THREAD

**Issue by Jazzmatazz** [reidobandedo/Goat-Of-The-Hill#74]
Timer on last 10 secs should Alert (or shake, etc) to let players know game is ending. Just to add more polish. Maybe also add a sound count down or ticking noise?

**Comment by ddh** [comment]
Wow you read my mind. I'm actually working on that right now. Making the last 10 seconds make the countdown larger and red.

**Comment by Jazzmatazz** [comment]
Perfect! 
Yea I was playing the game and it abruptly changed to score board and I was like.. heyyy I wasn't done kicking ass. lol

**Comment by ddh** [comment]
Done and done
